language: java
sudo: false
install:
- mvn install --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
- mvn deploy --settings .travis/settings.xml
cache:
  directories:
  - .autoconf
  - $HOME/.m2